### ISSUE TITLE
kotlinx-serialization 0.20.0 support?

### ISSUE THREAD

**Issue by peterfigure** [brudaswen/kotlinx-serialization-csv#1]
Unfortunately 0.14.0 is no longer compatible with more recent versions of Kotlin. I took a quick stab at porting the code, besides API changes it seems like there were some behavioural changes as well - have you taken a look yet?

**Comment by brudaswen** [comment]
Hey @peterfigure, Thanks a lot for pointing this out. A new version (`0.2.0`) has been pushed to *Maven Central* and should be available soon™.

**Comment by peterfigure** [comment]
Looks great, thanks @brudaswen !
