### ISSUE TITLE
Custom headers

### ISSUE THREAD

**Issue by peterfigure** [brudaswen/kotlinx-serialization-csv#2]
Is there a way to customize headers? Don't like saying this but perhaps with a custom annotation? :)

**Comment by brudaswen** [comment]
`@SerialName` should be supported:

```
@Serializable
data class SerialNameRecord(
    val first: Int,
    @SerialName("second") val b: Int
)
println(
    Csv(CsvConfiguration(hasHeaderRecord = true))
      .stringify(SerialNameRecord.serializer(), SerialNameRecord(1, 2))
)
// first,second
// 1,2
```
- https://github.com/brudaswen/kotlinx-serialization-csv/blob/master/library/src/test/kotlin/kotlinx/serialization/csv/config/CsvHasHeaderRecordTest.kt#L90
- https://github.com/brudaswen/kotlinx-serialization-csv/blob/master/library/src/test/kotlin/kotlinx/serialization/csv/records/SampleClasses.kt#L64

**Comment by peterfigure** [comment]
very cool thanks @brudaswen
